CREATE ENDPOINT [ServiceBrokerEndpoint] 
	STATE=STARTED
	AS TCP (LISTENER_PORT = 4022, LISTENER_IP = ALL)
	FOR SERVICE_BROKER (MESSAGE_FORWARDING = DISABLED
, MESSAGE_FORWARD_SIZE = 10
, AUTHENTICATION = WINDOWS NEGOTIATE
, ENCRYPTION = SUPPORTED ALGORITHM AES)